config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

# how to display restful routes individually
# resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, 
                    length: {minimum: 6, maximum: 100}
    validates :description, presence: true, 
                            length: {minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
    
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true, 
                        uniqueness: { case_sensitive: false },
                        length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                        uniqueness: { case_sensitive: false },
                        length: { maximum: 105 },
                        format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||=  User.find(session[:user_id]) if session[:user_id]
     
     end

     def logged_in?
        !!current_user
        
    end

    def require_user
        if !logged_in?
        flash[:alert] = "You must be logged in to perform that action"
        redirect_to login_path
        end
    
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [ :edit, :update, :destroy]

    def show     
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article was created successfully"
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
       if @article.update(article_params)
        flash[:notice] = "Article was updated successfully"
        redirect_to @article
       else
        render 'edit'
       end

    end

    def destroy
        @article.destroy
        redirect_to articles_path, status: :see_other
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
    if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own article"
        redirect_to @article
    end
    end



end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

    def new
        @category = Category.new

    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render 'new'
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category name updated successfully"
            redirect_to @category
        else
            render 'edit'
        end
    end

    def index
       
        @categories = Category.paginate(page: params[:page], per_page: 5)

    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "only admins can perform that action"
            redirect_to categories_path
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session] [:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "There was something wrong with your login details"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged Out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [ :edit, :update, :destroy]

def show
       
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
end

def index
    @users = User.paginate(page: params[:page], per_page: 5)
end

def new
    @user = User.new
end

def edit
   
end



def update
   
    if @user.update(user_params)
        flash[:notice] = "Your account information was successfully updated"
        redirect_to @user
    else
        render 'edit'
    end
end

def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
        redirect_to articles_path
    else
        render 'new'
    end

end

def destroy

    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
end




private 
def user_params
    params.require(:user).permit(:username, :email, :password)

end

def set_user
    @user = User.find(params[:id])
end

def require_same_user
    if current_user != @user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own account"
        redirect_to @user
    end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80 })
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address) 
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end

    

    
end

app/views/articles/_articles.html.erb
<div class="container">
        <% @articles.each do |article| %>
            <div class="row justify-content-center">
                <div class="col-8 mt-4">
                    <div class="card text-center shadow  mb-5 bg-body rounded">
                        <small class="card-header text-muted fw-light text-lowercase fst-italic">by <%= link_to article.user.username, user_path(article.user) %></small>
                        <% if article.categories.any? %>
                        <div class="p-1">  <%= render article.categories %></div>
                      <% end %>
                        <div class="card-body">
                            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "heading-styles" %></h5>
                            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                            <div class= "d-flex justify-content-center">
                                <%= link_to 'View', article_path(article), class: 'btn btn-outline-success m-1' %> 
                                <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                                    <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-outline-secondary m-1' %>
                                    <%= link_to 'Delete', article_path(article), class: "btn btn-outline-danger m-1", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }%>
                                <% end %>
                            </div>
                        </div>
                        <div class="card-footer fw-light text-muted">
                            <small>Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago.</small>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>

app/views/articles/_form.html.erb
<div class="container">


    <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'shared/errors', obj: @article %>
    <%= form_with(model: @article, class: "shadow p-3 mb-5 bg-light rounded", data: {turbo: false}) do |f| %>
        <div class="row mb-3">
            <%= f.label :title, class: "col-sm-2 col-form-label form-title-styles" %>
            <div class="col-sm-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
            </div>
        </div>

        <div class="row mb-3">
            <%= f.label :description, class: "col-sm-2 col-form-label  form-title-styles" %>
            <div class="col-sm-10">
            <%= f.text_area :description, class: "form-control shadow rounded", placeholder: "Description" %>
            </div>
        </div>

        <div class="row mb-3">
            <%= f.label :category, class: "col-sm-2 col-form-label  form-title-styles" %>
            <div class="col-sm-10">

            
                <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Make your selection from the list below" }, {multiple: true, size: 3, class: "form-select shadow rounded"}) %>
            
            
            
            </div>
        </div>

        <div class=" d-grid gap-2 d-md-flex justify-content-md-center">
            <%= f.submit class: "btn btn-outline-secondary" %>
        </div>
        </div>
    <% end %>

    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-dark text-center" %>
    </div>

</div>

app/views/articles/edit.html.erb
    <h1 class="text-center mt-4">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
    <h1 class="text-center mt-4">Listing All Articles</h1>
    <div class="flickr_pagination mt-4">
   
    <%= will_paginate @articles, :container => false %>
  </div>
  
    <%= render 'articles' %>

    <div class="flickr_pagination mb-4">
    
    <%= will_paginate @articles, :container => false %>
  </div>


 <%#   <div class="d-grid gap-2 col-6 mx-auto mb-4">
      <%= link_to 'Create New Article', new_article_path, class: "btn btn-outline-success"  %>
    </div>

app/views/articles/new.html.erb
    <h1 class="text-center mt-4">Create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
    <h2 class="text-center mt-4"><%= @article.title %></h2>
    <div class="container">
            <div class="row justify-content-center">
                <div class="col-8 mt-4">
                    <div class="card text-center shadow  mb-5 bg-body rounded">
                        <small class="card-header text-muted fw-light text-lowercase fst-italic">by <%= @article.user.username %>
                        <%= link_to gravatar_for(@article.user, size: 50), user_path(@article.user) %></small>
                        <% if @article.categories.any? %>
                          <div class="m-2">  <%= render @article.categories %></div>
                        <% end %>
                        <div class="card-body">
                            <div class="card-text text-start"><%= simple_format(@article.description) %></div>
                            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                            <div class= "d-flex justify-content-center"> 
                                <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-outline-secondary m-1' %>
                                <%= link_to 'Delete', article_path(@article), class: "btn btn-outline-danger m-1", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }%>
                            </div>
                            <% end %>
                        </div>
                        <div class="card-footer fw-light text-muted">
                            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago.</small>
                        </div>
                    </div>
                </div>
                <%= link_to '[ Return to articles listing ]', articles_path, class: "text-dark text-center" %>
            </div>
    </div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-secondary mx-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
    <%= form_with(model: @category, class: "shadow p-3 mb-5 bg-light rounded", data: {turbo: false}) do |f| %>
        <div class="row mb-3">
            <%= f.label :name, "Category Name", class: "col-sm-2 col-form-label form-title-styles" %>
            <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a category name" %>
            </div>
        </div>

        <div class=" d-grid gap-2 d-md-flex justify-content-md-center">
        <%= f.submit class: "btn btn-outline-secondary" %>
    </div>
    
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit Category Name</h1>

<div class="container">


    <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'form' %>

       

       
</div>
    <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-dark text-center" %>
    </div>

</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination mt-4">
   
    <%= will_paginate @categories, :container => false %>
  </div>

<div class="container">
        <% @categories.each do |category| %>
            <div class="row justify-content-center">
                <div class="col-6 mt-4">
                    <div class="card text-center shadow  mb-5 bg-body rounded">
                            <div class="card-body">
                                <h5 class="card-title"><%= link_to category.name, category_path(category), class: "heading-styles" %></h5>
                            </div>
                            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
                        
                        <div class="card-footer fw-light text-muted">
                            <small>Created <%= time_ago_in_words(category.created_at) %> ago, edited <%= time_ago_in_words(category.updated_at) %> ago.</small>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>

    <div class="flickr_pagination mb-4">
   
    <%= will_paginate @categories, :container => false %>
  </div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new Category</h1>

<div class="container">


    <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'form' %>

       

       
</div>
    <%= link_to '[ Cancel and return to categories listing ]', categories_path, class: "text-dark text-center" %>
    </div>

</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
        <%= link_to "Edit Category Name", edit_category_path(@category), class: "btn btn-outline-secondary m-1" %>
    </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>
<div class="flickr_pagination mt-4">
    
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles/articles' %>

<div class="flickr_pagination mb-4">
    
    <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3  text-secondary ">
    <div class="container d-flex justify-content-between align-items-center">
        <p class="col-md-6 p-1 mb-0 text-muted">Copyright © <%= link_to "Nicole Holland", "https://nicoleholland.ca", target: "blank", class: "text-muted" %></p>
         <ul id="footer-nav" class="nav col-md-6 p-1 justify-content-end">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Articles</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Users</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Login</a></li>
      
         </ul>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">

<% flash.each do |name, msg| %>
  
  <div class="alert  alert-<%= name =="notice" ? "success" : "danger" %>  alert-dismissable d-flex align-items-center justify-content-between my-3" role="alert">
  
  <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          
          <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    
                    
                  </li>
                  
                  
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Articles
                    </a>
                    <ul class="dropdown-menu">
                    <% if logged_in?  %>
                      <li><%= link_to "Create a New Article", new_article_path, class: "dropdown-item" %></li>
                      <% end %>
                      
                      <li><%= link_to "View Articles", articles_path, class: "dropdown-item" %></li>
                      
                    </ul>
                  </li>

                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Categories
                    </a>
                    <ul class="dropdown-menu">
                    <% if logged_in? && current_user.admin? %>
                      <li><%= link_to "Create a New Category", new_category_path, class: "dropdown-item" %></li>
                      <% end %>
                      
                      <li><%= link_to "View Categories", categories_path, class: "dropdown-item" %></li>
                      
                    </ul>
                  </li>

              <li class="nav-item">
              <%= link_to 'Users', users_path, class: "nav-link" %>
              </li>

               <% if logged_in? %>

               <li class="nav-item dropdown">
                    <div class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
                    </div>
                    <ul class="dropdown-menu">
                    
                      <li><%= link_to "View Your Profile", user_path(current_user), class: "dropdown-item" %></li>
                      <li><%= link_to "Edit Your Profile", edit_user_path(current_user), class: "dropdown-item" %></li>
                      <li><%= link_to "Delete Profile", user_path(current_user), class: "dropdown-item text-danger",  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></li>
                      
                    </ul>
                  </li>
               
                  <li class="nav-item">
                    <%= link_to 'Logout', logout_path, class: "nav-link", data: { turbo_method: :delete } %>
                  </li>
                <% else %>
                  
                  <li class="nav-item">
                    <%= link_to 'Login', login_path, class: "nav-link" %>
                  </li>

                  <li class="nav-item">
                    <%= link_to 'Sign Up', signup_path, class: "nav-link" %>
                  </li>

                <% end %>

              
             
          </div>
        </div>
      </nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Alpha Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="d-flex flex-column h-100">
  
    <%= render 'layouts/navigation' %>
    <div id="page-content">
     <%= render 'layouts/messages' %>
   
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="text-center mt-4">About Alpha Blog</h1>

<div class="container mt-4">
    <div class="row d-flex justify-content-center">
        <div class="col-8">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos vitae nesciunt nihil. Maiores veritatis, eaque ipsa nulla atque corporis. Soluta dolore esse officiis officia qui! Natus velit nihil est architecto, vitae iusto, dolor ex unde exercitationem magni illum sint ea officiis, praesentium recusandae laudantium aliquam expedita doloribus aperiam distinctio? Eveniet, quaerat facere saepe iste excepturi voluptate voluptatum deserunt veritatis delectus praesentium tempore nihil architecto cum, vitae totam possimus ratione alias est inventore illo iure quos! Delectus dolorum illum placeat repellendus, laudantium voluptate a corrupti, assumenda officiis iure magni aspernatur quas saepe exercitationem consequuntur! Quidem molestias eius aliquid quos rem quae.</p>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="d-flex flex-column justify-content-end">

<div class="container-fluid justify-content-center d-flex flex-column p-0" id="fleep">
  <div class="mt-0 p-5 text-center d-block position-relative">
    <div class=" rounded m-auto px-4 py-5 w-50 " id="home-hero-container">
      <h1 class="display-2 text-uppercase fw-bold">Alpha Blog</h1>
      <h3 class="text-secondary">Join us today!</h3>
      <%= link_to "Sign Up!", signup_path, class: "w-50 btn btn-outline-secondary btn-lg ms-auto mt-3" %>
      
      </div>
  </div>
  </div>

  <div class="container-fluid text-center p-2 justify-content-center d-flex flex-column w-75 mt-auto" >
  <h3 class="display-5">About the Alpha Blog project</h3>
 <p>Alpha Blog was created as part of my learning of Ruby on Rails, to help me thoroughly understand the many aspects of RoR I did not use Rails scaffolding for this project. In this project I utilised one-to-many associations, many-to-many associations, authentication systems, user validations, paginations and many other Rails functions. This project gave me experience with associations, front-end implementation, back-end implementation using REST architecture and deploying RoR apps to production.</p>
 <p>In this app you can sign up as a user and create articles, edit your own articles or delete your article. All articles are displayed in the Article index and Alpha Blog users are all displayed in the User index. Each article is linked to the user who created it and a category if a category was used in the article creation. Alpha Blog has the ability to add admin users, admin users have much broader access and are able to edit any article and delete users.</p>

  </div>
</div>

app/views/shared/_errors.html.erb
    <% if obj.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
            <div class="d-flex align-items-center justify-content-between mb-0">
                <h6 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved:</h6>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <ul class="mb-0 w-100">
                <% obj.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

app/views/users/_form.html.erb
<div class="container">


    <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'shared/errors', obj: @user %>
    <%= form_with(model: @user, class: "shadow p-3 mb-5 bg-light rounded", data: {turbo: false}) do |f| %>
        <div class="row mb-3">
            <%= f.label :username, class: "col-sm-2 col-form-label form-title-styles" %>
            <div class="col-sm-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
            </div>
        </div>

        <div class="row mb-3">
            <%= f.label :email, class: "col-sm-2 col-form-label  form-title-styles" %>
            <div class="col-sm-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email" %>
            </div>
        </div>

        <div class="row mb-3">
            <%= f.label :password, class: "col-sm-2 col-form-label  form-title-styles" %>
            <div class="col-sm-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
            </div>
        </div>

        <div class=" d-grid gap-2 d-md-flex justify-content-md-center">
            <%= f.submit(@user.new_record? ?  "Sign Up" : "Update Account", class: "btn btn-outline-secondary") %>
        </div>
        </div>
    <% end %>

    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-dark text-center" %>
    </div>

</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">All User Profiles</h1>

<div class="flickr_pagination mt-4">
    
<%= will_paginate @users, :container => false %>
</div>

<div class="container">
        <% @users.each do |user| %>
            <div class="row justify-content-center">
                <div class="col-8 mt-4">
                    <div class="card text-center shadow  mb-5 bg-body rounded">
                        <h5 class="card-header text-muted fw-light text-lowercase fst-italic"><%= link_to user.username, user %></h5>
                        <div class="card-body">
                            <div class="card-title"><%= link_to gravatar_for(user, size: 150), user %></div>
                            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
                            <div class= "d-flex justify-content-center">
                                <%= link_to 'View Profile', user, class: 'btn btn-outline-success m-1' %> 
                                <% if logged_in? %> 
                                <% if user == current_user %>
                                <%= link_to 'Edit Profile', edit_user_path(user), class: 'btn btn-outline-secondary m-1' %>
                                <% end %>
                                <% if current_user.admin? %>
                                <%= link_to "Delete User", user_path(user), class: "btn btn-outline-danger m-1", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the user account and all associated articles?" } %> 
                                <% end %>
                                <% end %>
                               
                            </div>
                        </div>
                        <div class="card-footer fw-light text-muted">
                            <small>Joined <%= time_ago_in_words(user.created_at) %> ago.</small>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>

    <div class="flickr_pagination mb-4">
    
<%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s Profile </h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
        <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-secondary m-1" %>
    </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>
<div class="flickr_pagination mt-4">
    
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles/articles' %>

<div class="flickr_pagination mb-4">
    
    <%= will_paginate @articles, :container => false %>
</div>